version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: ordermitra-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ordermitra
      POSTGRES_PASSWORD: ordermitra
      POSTGRES_DB: ordermitra
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ordermitra-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
